# Appium Server Configuration
appium.url=http://localhost:4723

# Device Configuration
device.name=emulator-5554
platform.version=16

# App Path (Update this with your actual APK path)
app.path=C:/Intern_Project_Code/task-01-mobile/build/app/outputs/flutter-apk/app-debug.apk

# Test User Credentials (User WITHOUT MFA)
test.email=nuwanthapiumal57@gmail.com
test.password=Nuwantha@1234

# Test User with MFA Enabled
test.email.with.mfa=nuwanthapiumal57+test3@gmail.com
test.password.with.mfa=Udara@1234

# MFA Secret Key (Base32 encoded - will be obtained after first MFA setup)
# Get this from Microsoft Authenticator or by running the test to extract from QR code
# This is for the test3 user who has MFA enabled
test.mfa.secret=OWYX4Z2VJCYOIBKVREBZGLWCPAYDMNWRQ27RWIU2ZZ2XPSX4LMTQ

# Test Configuration
implicit.wait=10
explicit.wait=20
